WORLD:
  TIME_LIMIT: 10000
  T: 0.01

GREEDY_AGENT:
  ID: 1
  TIME_LIMIT: 1

A_STAR_AGENT:
  ID: 2
  TIME_LIMIT: 10000

REAL_TIME_A_STAR_AGENT:
  ID: 3
  TIME_LIMIT: 2

RUN:
  INPUT_PATH: Inputs/input2.txt
  # [[Agent Type, Starting Vertex]]
  AGENTS: [[A_STAR_AGENT,1]]
